name: Build and Package Sudoku maven project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn clean package

      - name: Package as ZIP
        run: zip -r myproject.zip target/sudoku-1.0-SNAPSHOT.jar
        env:
          CI: true

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: sudoku.zip
          path: sudoku.zip